import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

import User from '../src/models/User';
import Resource from '../src/models/Resource';
import Transaction from '../src/models/Transaction';
import ScrapListing from '../src/models/ScrapListing';

const INDIAN_CITIES = [
    { city: 'Mumbai', state: 'Maharashtra', coordinates: [72.8777, 19.0760] as [number, number] },
    { city: 'Delhi', state: 'Delhi', coordinates: [77.1025, 28.7041] as [number, number] },
    { city: 'Bangalore', state: 'Karnataka', coordinates: [77.5946, 12.9716] as [number, number] },
    { city: 'Chennai', state: 'Tamil Nadu', coordinates: [80.2707, 13.0827] as [number, number] },
    { city: 'Hyderabad', state: 'Telangana', coordinates: [78.4867, 17.3850] as [number, number] },
    { city: 'Pune', state: 'Maharashtra', coordinates: [73.8567, 18.5204] as [number, number] },
    { city: 'Ahmedabad', state: 'Gujarat', coordinates: [72.5714, 23.0225] as [number, number] },
    { city: 'Coimbatore', state: 'Tamil Nadu', coordinates: [76.9558, 11.0168] as [number, number] },
    { city: 'Jaipur', state: 'Rajasthan', coordinates: [75.7873, 26.9124] as [number, number] },
    { city: 'Ludhiana', state: 'Punjab', coordinates: [75.8573, 30.9010] as [number, number] },
];

async function seed() {
    try {
        await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/econexus');
        console.log('✅ Connected to MongoDB');

        // Clear existing data
        await Promise.all([
            User.deleteMany({}),
            Resource.deleteMany({}),
            Transaction.deleteMany({}),
            ScrapListing.deleteMany({}),
        ]);
        console.log('🗑️ Cleared existing data');

        // Create Users
        const users = await User.create([
            {
                name: 'Admin User',
                email: 'admin@econexus.in',
                password: 'admin123',
                role: 'admin',
                company: 'EcoNexus Platform',
                phone: '+91-9876543210',
                location: { type: 'Point', ...INDIAN_CITIES[0] },
                reputation: 5.0,
            },
            {
                name: 'Rajesh Kumar',
                email: 'rajesh@tatasteels.in',
                password: 'password123',
                role: 'provider',
                company: 'Tata Steel Works',
                phone: '+91-9876543211',
                location: { type: 'Point', ...INDIAN_CITIES[0] },
                reputation: 4.8,
            },
            {
                name: 'Priya Sharma',
                email: 'priya@mahindra.in',
                password: 'password123',
                role: 'provider',
                company: 'Mahindra Manufacturing',
                phone: '+91-9876543212',
                location: { type: 'Point', ...INDIAN_CITIES[2] },
                reputation: 4.6,
            },
            {
                name: 'Amit Patel',
                email: 'amit@relianceindustries.in',
                password: 'password123',
                role: 'provider',
                company: 'Reliance Industries',
                phone: '+91-9876543213',
                location: { type: 'Point', ...INDIAN_CITIES[6] },
                reputation: 4.9,
            },
            {
                name: 'Deepa Nair',
                email: 'deepa@infosys.in',
                password: 'password123',
                role: 'provider',
                company: 'Infosys BPM Solutions',
                phone: '+91-9876543214',
                location: { type: 'Point', ...INDIAN_CITIES[4] },
                reputation: 4.3,
            },
            {
                name: 'Suresh Reddy',
                email: 'suresh@consumer1.in',
                password: 'password123',
                role: 'consumer',
                company: 'Reddy Enterprises',
                phone: '+91-9876543215',
                location: { type: 'Point', ...INDIAN_CITIES[3] },
                reputation: 4.5,
            },
            {
                name: 'Anjali Gupta',
                email: 'anjali@consumer2.in',
                password: 'password123',
                role: 'consumer',
                company: 'Gupta Tech Solutions',
                phone: '+91-9876543216',
                location: { type: 'Point', ...INDIAN_CITIES[1] },
                reputation: 4.2,
            },
            {
                name: 'Vikram Singh',
                email: 'vikram@consumer3.in',
                password: 'password123',
                role: 'consumer',
                company: 'Singh Manufacturing Co.',
                phone: '+91-9876543217',
                location: { type: 'Point', ...INDIAN_CITIES[5] },
                reputation: 4.7,
            },
            {
                name: 'Meera Krishnan',
                email: 'meera@provider5.in',
                password: 'password123',
                role: 'provider',
                company: 'Krishnan Metals Ltd.',
                phone: '+91-9876543218',
                location: { type: 'Point', ...INDIAN_CITIES[7] },
                reputation: 4.4,
            },
            {
                name: 'Arjun Mehta',
                email: 'arjun@provider6.in',
                password: 'password123',
                role: 'provider',
                company: 'Mehta Warehousing',
                phone: '+91-9876543219',
                location: { type: 'Point', ...INDIAN_CITIES[8] },
                reputation: 4.1,
            },
        ]);
        console.log(`👥 Created ${users.length} users`);

        const providers = users.filter((u) => u.role === 'provider');
        const consumers = users.filter((u) => u.role === 'consumer');

        const now = new Date();
        const threeMonthsLater = new Date(now.getTime() + 90 * 86400000);

        // Create Resources
        const resources = await Resource.create([
            {
                title: 'CNC Milling Machine — 5-Axis',
                type: 'machine',
                owner: providers[0]._id,
                description: 'High-precision 5-axis CNC milling machine, ideal for aerospace and automotive components. Tolerances up to ±0.001mm.',
                specifications: { brand: 'DMG Mori', model: 'DMU 50', axes: '5', spindleSpeed: '18000 RPM', tableSize: '630x500mm' },
                capacity: { value: 8, unit: 'hours/day' },
                location: { type: 'Point', ...INDIAN_CITIES[0] },
                availability: [
                    { dayOfWeek: 1, startTime: '08:00', endTime: '18:00' },
                    { dayOfWeek: 2, startTime: '08:00', endTime: '18:00' },
                    { dayOfWeek: 3, startTime: '08:00', endTime: '18:00' },
                    { dayOfWeek: 4, startTime: '08:00', endTime: '18:00' },
                    { dayOfWeek: 5, startTime: '08:00', endTime: '16:00' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'hourly', amount: 2500, currency: 'INR' },
                sustainabilityScore: 72,
                status: 'active',
                tags: ['cnc', 'milling', 'precision', 'aerospace'],
            },
            {
                title: 'Industrial Laser Cutting System',
                type: 'machine',
                owner: providers[1]._id,
                description: 'Fiber laser cutting system for sheet metal processing. 4kW power, capable of cutting up to 20mm mild steel.',
                specifications: { brand: 'Trumpf', model: 'TruLaser 3030', power: '4kW', bedSize: '3000x1500mm', accuracy: '±0.05mm' },
                capacity: { value: 12, unit: 'hours/day' },
                location: { type: 'Point', ...INDIAN_CITIES[2] },
                availability: [
                    { dayOfWeek: 1, startTime: '06:00', endTime: '22:00' },
                    { dayOfWeek: 2, startTime: '06:00', endTime: '22:00' },
                    { dayOfWeek: 3, startTime: '06:00', endTime: '22:00' },
                    { dayOfWeek: 4, startTime: '06:00', endTime: '22:00' },
                    { dayOfWeek: 5, startTime: '06:00', endTime: '22:00' },
                    { dayOfWeek: 6, startTime: '08:00', endTime: '14:00' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'hourly', amount: 3200, currency: 'INR' },
                sustainabilityScore: 65,
                status: 'active',
                tags: ['laser', 'cutting', 'sheet-metal', 'fiber'],
            },
            {
                title: 'Skilled Welding Team (6 certified)',
                type: 'labor',
                owner: providers[0]._id,
                description: 'Team of 6 AWS-certified welders specializing in TIG, MIG, and Arc welding. Experience with structural steel and pressure vessels.',
                specifications: { teamSize: '6', certifications: 'AWS D1.1, ASME IX', experience: '8+ years avg' },
                capacity: { value: 6, unit: 'workers' },
                location: { type: 'Point', ...INDIAN_CITIES[0] },
                availability: [
                    { dayOfWeek: 1, startTime: '08:00', endTime: '17:00' },
                    { dayOfWeek: 2, startTime: '08:00', endTime: '17:00' },
                    { dayOfWeek: 3, startTime: '08:00', endTime: '17:00' },
                    { dayOfWeek: 4, startTime: '08:00', endTime: '17:00' },
                    { dayOfWeek: 5, startTime: '08:00', endTime: '17:00' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'daily', amount: 18000, currency: 'INR' },
                sustainabilityScore: 80,
                status: 'active',
                tags: ['welding', 'tig', 'mig', 'certified', 'labor'],
            },
            {
                title: 'Insulated Warehouse — 5000 sqft',
                type: 'warehouse',
                owner: providers[2]._id,
                description: 'Climate-controlled insulated warehouse with loading docks. Suitable for temperature-sensitive materials and finished goods.',
                specifications: { area: '5000 sqft', height: '25ft', docks: '2', racking: 'Pallet & selective', security: '24/7 CCTV + guards' },
                capacity: { value: 5000, unit: 'sqft' },
                location: { type: 'Point', ...INDIAN_CITIES[6] },
                availability: [
                    { dayOfWeek: 0, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 1, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 2, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 3, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 4, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 5, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 6, startTime: '00:00', endTime: '23:59' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'monthly', amount: 85000, currency: 'INR' },
                sustainabilityScore: 88,
                status: 'active',
                tags: ['warehouse', 'storage', 'insulated', 'climate-controlled'],
            },
            {
                title: 'Industrial Forklift Fleet (3 units)',
                type: 'machine',
                owner: providers[2]._id,
                description: 'Fleet of 3 Toyota forklifts with trained operators. Load capacity 2.5T each. Available for factory and warehouse operations.',
                specifications: { brand: 'Toyota', capacity: '2.5T each', units: '3', fuelType: 'Electric' },
                capacity: { value: 3, unit: 'units' },
                location: { type: 'Point', ...INDIAN_CITIES[6] },
                availability: [
                    { dayOfWeek: 1, startTime: '07:00', endTime: '19:00' },
                    { dayOfWeek: 2, startTime: '07:00', endTime: '19:00' },
                    { dayOfWeek: 3, startTime: '07:00', endTime: '19:00' },
                    { dayOfWeek: 4, startTime: '07:00', endTime: '19:00' },
                    { dayOfWeek: 5, startTime: '07:00', endTime: '19:00' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'daily', amount: 12000, currency: 'INR' },
                sustainabilityScore: 91,
                status: 'active',
                tags: ['forklift', 'material-handling', 'electric'],
            },
            {
                title: 'Assembly Line Workers (10-person crew)',
                type: 'labor',
                owner: providers[3]._id,
                description: 'Trained assembly line workers with experience in electronics and automotive assembly. Quality-checked and safety-certified.',
                specifications: { teamSize: '10', experience: '5+ years', certifications: 'ISO 9001 trained' },
                capacity: { value: 10, unit: 'workers' },
                location: { type: 'Point', ...INDIAN_CITIES[4] },
                availability: [
                    { dayOfWeek: 1, startTime: '08:00', endTime: '16:00' },
                    { dayOfWeek: 2, startTime: '08:00', endTime: '16:00' },
                    { dayOfWeek: 3, startTime: '08:00', endTime: '16:00' },
                    { dayOfWeek: 4, startTime: '08:00', endTime: '16:00' },
                    { dayOfWeek: 5, startTime: '08:00', endTime: '16:00' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'daily', amount: 32000, currency: 'INR' },
                sustainabilityScore: 75,
                status: 'active',
                tags: ['assembly', 'electronics', 'automotive', 'labor'],
            },
            {
                title: 'Cold Storage Facility — 2000 sqft',
                type: 'warehouse',
                owner: providers[4]._id,
                description: 'Refrigerated cold storage facility with temperature control from -20°C to +10°C. FSSAI compliant with automated monitoring.',
                specifications: { area: '2000 sqft', tempRange: '-20°C to +10°C', compliance: 'FSSAI', monitoring: 'IoT sensors' },
                capacity: { value: 2000, unit: 'sqft' },
                location: { type: 'Point', ...INDIAN_CITIES[7] },
                availability: [
                    { dayOfWeek: 0, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 1, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 2, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 3, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 4, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 5, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 6, startTime: '00:00', endTime: '23:59' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'monthly', amount: 120000, currency: 'INR' },
                sustainabilityScore: 60,
                status: 'active',
                tags: ['cold-storage', 'refrigeration', 'FSSAI'],
            },
            {
                title: 'Hydraulic Press — 100 Ton',
                type: 'machine',
                owner: providers[4]._id,
                description: '100-ton hydraulic press for metal forming, stamping, and molding operations. Programmable PLC controls.',
                specifications: { brand: 'Schuler', tonnage: '100T', bedSize: '1200x800mm', stroke: '400mm', plc: 'Siemens S7' },
                capacity: { value: 10, unit: 'hours/day' },
                location: { type: 'Point', ...INDIAN_CITIES[7] },
                availability: [
                    { dayOfWeek: 1, startTime: '06:00', endTime: '20:00' },
                    { dayOfWeek: 2, startTime: '06:00', endTime: '20:00' },
                    { dayOfWeek: 3, startTime: '06:00', endTime: '20:00' },
                    { dayOfWeek: 4, startTime: '06:00', endTime: '20:00' },
                    { dayOfWeek: 5, startTime: '06:00', endTime: '18:00' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'hourly', amount: 1800, currency: 'INR' },
                sustainabilityScore: 55,
                status: 'active',
                tags: ['hydraulic', 'press', 'metal-forming', 'stamping'],
            },
            {
                title: 'Open Yard Storage — 10000 sqft',
                type: 'warehouse',
                owner: providers[5]._id,
                description: 'Fenced open yard with concrete flooring for heavy equipment and raw material storage. Crane access available.',
                specifications: { area: '10000 sqft', surfacing: 'Concrete', craneAccess: 'Yes', fencing: 'Compound wall + razor wire' },
                capacity: { value: 10000, unit: 'sqft' },
                location: { type: 'Point', ...INDIAN_CITIES[8] },
                availability: [
                    { dayOfWeek: 0, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 1, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 2, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 3, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 4, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 5, startTime: '00:00', endTime: '23:59' },
                    { dayOfWeek: 6, startTime: '00:00', endTime: '23:59' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'monthly', amount: 45000, currency: 'INR' },
                sustainabilityScore: 82,
                status: 'active',
                tags: ['open-yard', 'heavy-equipment', 'raw-material'],
            },
            {
                title: 'Quality Inspection Team (4 engineers)',
                type: 'labor',
                owner: providers[1]._id,
                description: 'NDT-certified quality inspection team with portable testing equipment. Can handle dimensional, visual, and ultrasonic testing.',
                specifications: { teamSize: '4', certifications: 'ASNT Level II, ISO 17025', equipment: 'UT, MT, PT kits' },
                capacity: { value: 4, unit: 'engineers' },
                location: { type: 'Point', ...INDIAN_CITIES[2] },
                availability: [
                    { dayOfWeek: 1, startTime: '09:00', endTime: '18:00' },
                    { dayOfWeek: 2, startTime: '09:00', endTime: '18:00' },
                    { dayOfWeek: 3, startTime: '09:00', endTime: '18:00' },
                    { dayOfWeek: 4, startTime: '09:00', endTime: '18:00' },
                    { dayOfWeek: 5, startTime: '09:00', endTime: '18:00' },
                ],
                availableFrom: now,
                availableTo: threeMonthsLater,
                priceModel: { type: 'daily', amount: 22000, currency: 'INR' },
                sustainabilityScore: 70,
                status: 'active',
                tags: ['inspection', 'quality', 'NDT', 'testing'],
            },
        ]);
        console.log(`📦 Created ${resources.length} resources`);

        // Create Transactions
        const transactions = await Transaction.create([
            {
                resource: resources[0]._id,
                provider: providers[0]._id,
                consumer: consumers[0]._id,
                status: 'payment_released',
                amount: 20000,
                escrowAmount: 20000,
                startDate: new Date(now.getTime() - 20 * 86400000),
                endDate: new Date(now.getTime() - 19 * 86400000),
                timeline: [
                    { event: 'Booking requested', status: 'requested', timestamp: new Date(now.getTime() - 22 * 86400000) },
                    { event: 'Approved', status: 'approved', timestamp: new Date(now.getTime() - 21 * 86400000) },
                    { event: 'Payment locked', status: 'payment_locked', timestamp: new Date(now.getTime() - 20 * 86400000) },
                    { event: 'Service completed', status: 'completed', timestamp: new Date(now.getTime() - 19 * 86400000) },
                    { event: 'Payment released', status: 'payment_released', timestamp: new Date(now.getTime() - 18 * 86400000) },
                ],
                rating: { providerRating: 5, consumerRating: 4, review: 'Excellent CNC work!' },
            },
            {
                resource: resources[3]._id,
                provider: providers[2]._id,
                consumer: consumers[1]._id,
                status: 'payment_released',
                amount: 85000,
                escrowAmount: 85000,
                startDate: new Date(now.getTime() - 35 * 86400000),
                endDate: new Date(now.getTime() - 5 * 86400000),
                timeline: [
                    { event: 'Booking requested', status: 'requested', timestamp: new Date(now.getTime() - 40 * 86400000) },
                    { event: 'Approved', status: 'approved', timestamp: new Date(now.getTime() - 39 * 86400000) },
                    { event: 'Payment locked', status: 'payment_locked', timestamp: new Date(now.getTime() - 35 * 86400000) },
                    { event: 'Service completed', status: 'completed', timestamp: new Date(now.getTime() - 5 * 86400000) },
                    { event: 'Payment released', status: 'payment_released', timestamp: new Date(now.getTime() - 4 * 86400000) },
                ],
                rating: { providerRating: 4, consumerRating: 5, review: 'Great warehouse, well maintained.' },
            },
            {
                resource: resources[1]._id,
                provider: providers[1]._id,
                consumer: consumers[2]._id,
                status: 'approved',
                amount: 32000,
                escrowAmount: 0,
                startDate: new Date(now.getTime() + 3 * 86400000),
                endDate: new Date(now.getTime() + 4 * 86400000),
                timeline: [
                    { event: 'Booking requested', status: 'requested', timestamp: new Date(now.getTime() - 1 * 86400000) },
                    { event: 'Approved', status: 'approved', timestamp: new Date() },
                ],
            },
            {
                resource: resources[2]._id,
                provider: providers[0]._id,
                consumer: consumers[0]._id,
                status: 'requested',
                amount: 54000,
                escrowAmount: 0,
                startDate: new Date(now.getTime() + 5 * 86400000),
                endDate: new Date(now.getTime() + 8 * 86400000),
                timeline: [
                    { event: 'Booking requested', status: 'requested', timestamp: new Date() },
                ],
            },
        ]);
        console.log(`💰 Created ${transactions.length} transactions`);

        // Create Scrap Listings
        const scrapListings = await ScrapListing.create([
            {
                title: 'Mild Steel Scrap — Grade A',
                category: 'ferrous_metal',
                seller: providers[0]._id,
                description: 'Clean mild steel scrap from CNC operations. Chips and turnings, free of oil contamination.',
                quantity: 5000,
                unit: 'kg',
                pricePerUnit: 30,
                marketRate: 28.5,
                location: { type: 'Point', ...INDIAN_CITIES[0] },
                quality: 'premium',
                certifications: ['ISO 14001'],
                minOrderQuantity: 500,
                status: 'available',
            },
            {
                title: 'Copper Wire Scrap',
                category: 'non_ferrous_metal',
                seller: providers[3]._id,
                description: 'Insulated copper wire scrap from electrical maintenance. Copper content ~85%.',
                quantity: 800,
                unit: 'kg',
                pricePerUnit: 450,
                marketRate: 485,
                location: { type: 'Point', ...INDIAN_CITIES[4] },
                quality: 'standard',
                certifications: [],
                minOrderQuantity: 100,
                status: 'available',
            },
            {
                title: 'HDPE Drums — Used',
                category: 'plastic',
                seller: providers[2]._id,
                description: 'Used HDPE drums (200L capacity). Triple-rinsed, food-grade approved. Ideal for recycling or reuse.',
                quantity: 200,
                unit: 'units',
                pricePerUnit: 350,
                marketRate: 400,
                location: { type: 'Point', ...INDIAN_CITIES[6] },
                quality: 'standard',
                certifications: ['FSSAI'],
                minOrderQuantity: 20,
                status: 'available',
            },
            {
                title: 'Aluminum Extrusion Scrap',
                category: 'non_ferrous_metal',
                seller: providers[1]._id,
                description: 'Clean aluminum extrusion offcuts. Alloy 6061-T6. No contamination.',
                quantity: 1200,
                unit: 'kg',
                pricePerUnit: 180,
                marketRate: 185,
                location: { type: 'Point', ...INDIAN_CITIES[2] },
                quality: 'premium',
                certifications: ['Material Test Certificate'],
                minOrderQuantity: 200,
                status: 'available',
            },
            {
                title: 'E-Waste — Circuit Boards',
                category: 'electronic',
                seller: providers[4]._id,
                description: 'Assorted electronic circuit boards from decommissioned equipment. Contains recoverable gold, silver, and copper.',
                quantity: 300,
                unit: 'kg',
                pricePerUnit: 380,
                marketRate: 350,
                location: { type: 'Point', ...INDIAN_CITIES[7] },
                quality: 'economy',
                certifications: ['E-Waste Authorization'],
                minOrderQuantity: 50,
                status: 'available',
            },
            {
                title: 'Industrial Rubber Sheets',
                category: 'rubber',
                seller: providers[5]._id,
                description: 'Used conveyor belt rubber sheets. Thickness 8-12mm. Suitable for recycling into mats and tiles.',
                quantity: 2000,
                unit: 'kg',
                pricePerUnit: 14,
                marketRate: 12,
                location: { type: 'Point', ...INDIAN_CITIES[8] },
                quality: 'standard',
                certifications: [],
                minOrderQuantity: 200,
                status: 'available',
            },
        ]);
        console.log(`♻️ Created ${scrapListings.length} scrap listings`);

        console.log('\n🎉 Seed completed successfully!');
        console.log('\n📋 Login credentials:');
        console.log('   Admin:    admin@econexus.in / admin123');
        console.log('   Provider: rajesh@tatasteels.in / password123');
        console.log('   Consumer: suresh@consumer1.in / password123');

        process.exit(0);
    } catch (error) {
        console.error('❌ Seed error:', error);
        process.exit(1);
    }
}

seed();
